function el<T extends HTMLElement>(id: string) {
  return document.getElementById(id) as T
}

export const ui = {
  pane: el<HTMLDivElement>('pane'),
  canvas: el<HTMLCanvasElement>('graph'),
  tube: el<HTMLCanvasElement>('tube'),
  svg: el<HTMLElement>('overlay-svg') as unknown as SVGSVGElement,
  html: el<HTMLDivElement>('overlay-html'),
  facets: el<HTMLDivElement>('facets'),
  legends: el<HTMLDivElement>('legends'),
  info: el<HTMLDivElement>('info'),
  announce: el<HTMLDivElement>('announce'),
  loading: el<HTMLDivElement>('loading'),
  loadingText: el<HTMLSpanElement>('loading-text'),
  loadingTime: el<HTMLSpanElement>('loading-time'),
  cancel: el<HTMLButtonElement>('cancel'),
  toast: el<HTMLDivElement>('toast'),
  toastText: el<HTMLSpanElement>('toast-text'),
  toastActions: el<HTMLSpanElement>('toast-actions'),
  toastClose: el<HTMLButtonElement>('toast-close'),
  back: el<HTMLButtonElement>('back'),
  caption: el<HTMLDivElement>('caption'),
  hint: el<HTMLDivElement>('hint'),
  hintClose: el<HTMLButtonElement>('hint-close'),
  help: el<HTMLButtonElement>('help'),
  helpDialog: el<HTMLDialogElement>('help-dialog'),
  zoomIn: el<HTMLButtonElement>('zoom-in'),
  zoomOut: el<HTMLButtonElement>('zoom-out'),
  zoomFit: el<HTMLButtonElement>('zoom-fit'),
  empty: el<HTMLDivElement>('empty'),
  stats: el<HTMLSpanElement>('stats'),
  menus: el<HTMLElement>('menus'),
  findForm: el<HTMLFormElement>('find-form'),
  find: el<HTMLInputElement>('find'),
  findList: el<HTMLDataListElement>('find-list'),
  file: el<HTMLInputElement>('file'),
  open: el<HTMLButtonElement>('open'),
  emptyOpen: el<HTMLButtonElement>('empty-open'),
  openDialog: el<HTMLDialogElement>('open-dialog'),
  openFile: el<HTMLButtonElement>('open-file'),
  openGbz: el<HTMLButtonElement>('open-gbz'),
  recent: el<HTMLElement>('recent'),
  recentList: el<HTMLUListElement>('recent-list'),
  url: el<HTMLInputElement>('url'),
  gbzDialog: el<HTMLDialogElement>('gbz-dialog'),
  gbzDb: el<HTMLInputElement>('gbz-db'),
  gbzIndex: el<HTMLInputElement>('gbz-index'),
  gbzRegion: el<HTMLInputElement>('gbz-region'),
  gbzHaplotypes: el<HTMLInputElement>('gbz-haplotypes'),
  referenceDialog: el<HTMLDialogElement>('reference-dialog'),
  referenceStatus: el<HTMLParagraphElement>('reference-status'),
  genomeSearch: el<HTMLInputElement>('genome-search'),
  genomeResults: el<HTMLUListElement>('genome-results'),
  genomeHint: el<HTMLParagraphElement>('genome-hint'),
  referenceChosen: el<HTMLElement>('reference-chosen'),
  referenceGenesRow: el<HTMLLabelElement>('reference-genes-row'),
  referenceGenes: el<HTMLSelectElement>('reference-genes'),
  referenceContigs: el<HTMLDivElement>('reference-contigs'),
  referenceRememberRow: el<HTMLLabelElement>('reference-remember-row'),
  referenceRemember: el<HTMLInputElement>('reference-remember'),
  referenceRememberText: el<HTMLSpanElement>('reference-remember-text'),
  referenceHubs: el<HTMLDetailsElement>('reference-hubs'),
  hubList: el<HTMLUListElement>('hub-list'),
  hubUrl: el<HTMLInputElement>('hub-url'),
  hubAdd: el<HTMLButtonElement>('hub-add'),
  referenceApply: el<HTMLButtonElement>('reference-apply'),
}
